### ISSUE TITLE
Clarify MCPX dumping in README

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/xbox-tools#1]
From the README:

> Dumping the secret southbridge ROM (including the RC4 Key) is very hard and not possible (yet?).

This is not factually true. Ofcourse the MCPX is dumpable. Just not through homebrew / these tools.

**Comment by CodeAsm** [comment]
did you open this yourself or is the author gone?

**Comment by JayFoxRox** [comment]
Done
