### ISSUE TITLE
Eject script?

### ISSUE THREAD

**Issue by mreassassin** [JayFoxRox/xbox-tools#69]
My Xbox one x eject button doesn’t respond anymore.  No sounds.  No ejects.  Nothing. Is there a script that can do this for me?  Or do I need to take it to Microsoft?

**Comment by dracc** [comment]
These tools are aimed towards the original Xbox released back in 2001. I'm not saying JayFoxRox doesn't have a solution for you, just that this repo is aimed towards a different product. :)

**Comment by JayFoxRox** [comment]
What @dracc said.

Contact Microsoft about your issues or people from that scene - I can't help with that.

Closed as invalid.
